export const DWConfig = {};

DWConfig.WeaponDamageType = {
    eng: "Energy",
    exp: "Explosive",
    imp: "Impact",
    rnd: "Rending"
}

DWConfig.CharacteristicWords = {
    "ws": "Weapon Skill",
    "bs": "Ballistic Skill",
    "str": "Strength",
    "tg": "Toughness",
    "ag": "Agility",
    "int": "Intelligence",
    "per": "Perception",
    "wil": "Willpower",
    "fs": "Fellowship"
};

DWConfig.TestDifficulties = {
    "trivial": { label: "Trivial", modifier: 60 },
    "elementary": { label: "Elementary", modifier: 50 },    
    "simple": { label: "Simple", modifier: 40 },    
    "easy": { label: "Easy", modifier: 30 },
    "routine": { label: "Routine", modifier: 20 },
    "ordinary": { label: "Ordinary", modifier: 10 },
    "challenging": { label: "Challenging", modifier: 0 },
    "difficult": { label: "Difficult", modifier: -10 },
    "hard": { label: "Hard", modifier: -20 },
    "very-hard": { label: "Very Hard", modifier: -30 },
    "arduous": { label: "Arduous", modifier: -40 },
    "punishing": { label: "Punishing", modifier: -50 },
    "hellish": { label: "Hellish", modifier: -60 }
};

DWConfig.Skills = {
    "awareness": "Awareness",
    "carouse": "Carouse",
    "charm": "Charm",
    "climb": "Climb",
    "concealment": "Concealment",
    "contortionist": "Contortionist",
    "deceive": "Deceive",
    "dodge": "Dodge",
    "evaluate": "Evaluate",
    "gamble": "Gamble",
    "inquiry": "Inquiry",
    "intimidate": "Intimidate",
    "logic": "Logic",
    "scrutiny": "Scrutiny",
    "search": "Search",
    "silent_move": "Silent Move",
    "swim": "Swim",
    "acrobatics": "Acrobatics",
    "athletics": "Athletics",
    "command": "Command",
    "chem_use": "Chem-Use",
    "cipher_xenos_markings": "Cipher - Xenos Markings",
    "cipher_deathwatch": "Cipher - Deathwatch",
    "cipher_chapter_runes": "Cipher - Chapter Runes",
    "cipher_imperial_codes": "Cipher - Imperial Codes",
    "cipher_mercenary_cant": "Cipher - Mercenary Cant",
    "cipher_inquisition": "Cipher - Inquisition",
    "cipher_underworld": "Cipher - Underworld",
    "demolitions": "Demolitions",
    "drive_ground": "Drive - Ground",
    "drive_hover_skimmer": "Drive - Hover/Skimmer",
    "drive_walker": "Drive - Walker",
    "interrogation": "Interrogation",
    "invocation": "Invocation",
    "lip_reading": "Lip Reading",
    "literacty": "Literacy",
    "lore_common_adeptus_arbites": "Lore Common: Adeptus Arbites",
    "lore_common_adeptus_astartes": "Lore Common: Adeptus Astartes",
    "lore_common_adeptus_mechanicus": "Lore Common: Adeptus Mechanicus",
    "lore_common_administratum": "Lore Common: Administratum",
    "lore_common_deathwatch": "Lore Common: Deathwatch",
    "lore_common_ecclesiarchy": "Lore Common: Ecclesiarchy",
    "lore_common_imperial_creed": "Lore Common: Imperial Creed",
    "lore_common_imperial_guard": "Lore Common: Imperial Guard",
    "lore_common_imperial_navy": "Lore Common: Imperial Navy",
    "lore_common_imperium": "Lore Common: Imperium",
    "lore_common_jericho_reach": "Lore Common: Jericho Reach",
    "lore_common_tech": "Lore Common: Tech",
    "lore_common_war": "Lore Common: War",
    "lore_forbidden_adeptus_astartes": "Lore: Forbidden - Adeptus Astartes",
    "lore_forbidden_adeptus_mechanicus": "Lore: Forbidden - Adeptus Mechanicus",
    "lore_forbidden_archeotech": "Lore: Forbidden - Archeotech",
    "lore_forbidden_black_library": "Lore: Forbidden - The Black Library",
    "lore_forbidden_daemonology": "Lore: Forbidden - Daemonology",
    "lore_forbidden_heresy": "Lore: Forbidden - Heresy",
    "lore_forbidden_inquisition": "Lore: Forbidden - The Inquisition",
    "lore_forbidden_mutants": "Lore: Forbidden - Mutants",
    "lore_forbidden_psykers": "Lore: Forbidden - Psykers",
    "lore_forbidden_traitor_legions": "Lore: Forbidden - The Traitor Legions",
    "lore_forbidden_warp": "Lore: Forbidden - The Warp",
    "lore_forbidden_xenos": "Lore: Forbidden - Xenos",
    "lore_scholastic_archaic": "Lore: Scholastic - Archaic",
    "lore_scholastic_astromancy": "Lore: Scholastic - Astromancy",
    "lore_scholastic_beasts": "Lore: Scholastic - Beasts",
    "lore_scholastic_bureaucracy": "Lore: Scholastic - Bureaucracy",
    "lore_scholastic_chymistry": "Lore: Scholastic - Chymistry",
    "lore_scholastic_codex_astartes": "Lore: Scholastic - Codex Astartes",
    "lore_scholastic_cryptology": "Lore: Scholastic - Cryptology",
    "lore_scholastic_heraldry": "Lore: Scholastic - Heraldry",
    "lore_scholastic_imperial_creed": "Lore: Scholastic - Imperial Creed",
    "lore_scholastic_judgement": "Lore: Scholastic - Judgement",
    "lore_scholastic_legend": "Lore: Scholastic - Legend",
    "lore_scholastic_numerology": "Lore: Scholastic - Numerology",
    "lore_scholastic_occult": "Lore: Scholastic - Occult",
    "lore_scholastic_philosophy": "Lore: Scholastic - Philosophy",
    "lore_scholastic_tactica_imperialis": "Lore: Scholastic - Tactica Imperialis",
    "medicae": "Medicae",
    "navigation_surface": "Navigation - Surface",
    "navigation_stellar": "Navigation - Stellar",
    "performer_dancer": "Performer - Dancer",
    "performer_musician": "Performer - Musician",
    "performer_singer": "Performer - Singer",
    "performer_storyteller": "Performer - Storyteller",
    "pilot_personal": "Pilot - Personal",
    "pilot_flyer": "Pilot - Flyer",
    "pilot_space_craft": "Pilot - Space Craft",
    "psyniscience": "Psyniscience",
    "security": "Security",
    "shadowing": "Shadowing",
    "slight_of_hand": "Sleight of Hand",
    "speak_language_eldar": "Speak Language - Eldar",
    "speak_language_high_gothic": "Speak Language - Hight Gothic",
    "speak_language_kroot": "Speak Language - Kroot",
    "speak_language_low_gothic": "Speak Language - Low Gothic",
    "speak_language_ork": "Speak Language - Ork",
    "speak_language_techna_lingua": "Speak Language - Techna-Lingua",
    "speak_language_tau": "Speak Language - Tau",
    "survival": "Survival",
    "tactics_air_combat": "Tactics - Air Combat",
    "tactics_armoured": "Tactics - Armoured",
    "tactics_assault_doctrine": "Tactics - Assault Doctrine",
    "tactics_defensive_doctrine": "Tactics - Defensive Doctrine",
    "tactics_orbital_drop": "Tactics - Orbital Drop",
    "tactics_recon_and_stealth": "Tactics - Recon and Stealth",
    "tech_use": "Tech-Use",
    "tracking": "Tracking",
    "trade_archaeologist": "Trade - Archaeologist",
    "trade_armourer": "Trade - Armourer",
    "trade_astrographer": "Trade - Astrographer",
    "trade_chymist": "Trade - Chymist",
    "trade_cryptographer": "Trade - Cryptographer",
    "trade_explorer": "Trade - Explorer",
    "trade_linguist": "Trade - Linguist",
    "trade_remembrancer": "Trade - Remembrancer",
    "trade_shipwright": "Trade - Shipwright",
    "trade_soothsayer": "Trade - Soothsayer",
    "trade_technomat": "Trade - Technomat",
    "trade_trader": "Trade - Trader",
    "wrangling": "Wrangling"
};